/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cmcc_nativepackage_IDCard */

#ifndef _Included_com_cmcc_nativepackage_IDCard
#define _Included_com_cmcc_nativepackage_IDCard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cmcc_nativepackage_IDCard
 * Method:    openIDCard
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cmcc_nativepackage_UsbIDCard_openIDCard
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_cmcc_nativepackage_IDCard
 * Method:    closeIDCard
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cmcc_nativepackage_UsbIDCard_closeIDCard
  (JNIEnv *, jclass);

/*
 * Class:     com_cmcc_nativepackage_IDCard
 * Method:    getIDCardVersion
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_cmcc_nativepackage_UsbIDCard_getIDCardVersion
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_cmcc_nativepackage_IDCard
 * Method:    initialIDCard
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cmcc_nativepackage_UsbIDCard_initialIDCard
  (JNIEnv *, jclass);

/*
 * Class:     com_cmcc_nativepackage_IDCard
 * Method:    getIdCardInfo
 * Signature: ([Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_cmcc_nativepackage_UsbIDCard_getIdCardInfo
  (JNIEnv *, jclass, jobjectArray, jbyteArray);

JNIEXPORT jint JNICALL Java_com_cmcc_nativepackage_UsbIDCard_isOTGDevice(
 		JNIEnv *env, jclass cls);

JNIEXPORT jint JNICALL Java_com_cmcc_nativepackage_UsbIDCard_getDevicePermission(
		JNIEnv *env, jclass cls);

#ifdef __cplusplus
}
#endif
#endif
